import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-dim": "#d6dbd5",
        "on-surface": "#171d19",
        "error": "#ba1a1a",
        "outline": "#6e7a71",
        "on-secondary-fixed-variant": "#7300a1",
        "on-tertiary-fixed": "#251a00",
        "on-background": "#171d19",
        "on-secondary-container": "#470065",
        "surface-container-low": "#f0f5ee",
        "outline-variant": "#bdcabf",
        "primary-fixed-dim": "#75daa3",
        "on-tertiary-container": "#3a2a00",
        "tertiary": "#785a00",
        "on-tertiary-fixed-variant": "#5b4300",
        "background": "#f6fbf4",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2c322d",
        "inverse-on-surface": "#edf2eb",
        "primary-fixed": "#91f7bd",
        "on-primary-container": "#00341e",
        "primary": "#006d44",
        "secondary-fixed-dim": "#e9b3ff",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#310048",
        "surface-container": "#eaefe9",
        "surface-container-high": "#e4eae3",
        "secondary-container": "#cb5fff",
        "surface": "#f6fbf4",
        "on-primary-fixed-variant": "#005232",
        "tertiary-container": "#ba8d02",
        "surface-bright": "#f6fbf4",
        "inverse-primary": "#75daa3",
        "on-error": "#ffffff",
        "surface-variant": "#dfe4dd",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#f2bf41",
        "tertiary-fixed": "#ffdf9b",
        "primary-container": "#3fa673",
        "on-primary-fixed": "#002111",
        "surface-tint": "#006d44",
        "on-surface-variant": "#3e4941",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#f7d8ff",
        "surface-container-highest": "#dfe4dd",
        "secondary": "#931ec7"
      },
      borderRadius: {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      spacing: {
          "md": "24px",
          "sm": "12px",
          "lg": "48px",
          "base": "8px",
          "xs": "4px",
          "gutter": "24px",
          "xl": "80px",
          "container-max": "1280px"
      },
      fontFamily: {
          "h2": ["Manrope"],
          "body-sm": ["Manrope"],
          "label-bold": ["Manrope"],
          "h3": ["Manrope"],
          "h1": ["Manrope"],
          "caption": ["Manrope"],
          "body-md": ["Manrope"],
          "body-lg": ["Manrope"],
          "display": ["Manrope"]
      },
      fontSize: {
          "h2": ["24px", {"lineHeight": "1.4", "fontWeight": "700"}],
          "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
          "label-bold": ["14px", {"lineHeight": "1.2", "fontWeight": "700"}],
          "h3": ["20px", {"lineHeight": "1.4", "fontWeight": "600"}],
          "h1": ["32px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "700"}],
          "caption": ["12px", {"lineHeight": "1.2", "fontWeight": "500"}],
          "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
          "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
          "display": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
} satisfies Config;
